version: "3.8"
services:
  postgresDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=QUIZ
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5436:5432"